# Generated by Django 5.1.4 on 2025-01-18 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tourphoto',
            name='tour',
        ),
        migrations.RemoveField(
            model_name='tourinclusion',
            name='tour',
        ),
        migrations.RemoveField(
            model_name='tourdate',
            name='tour',
        ),
        migrations.RemoveField(
            model_name='tourhighlight',
            name='tour',
        ),
        migrations.RemoveField(
            model_name='tourexclusion',
            name='tour',
        ),
        migrations.RemoveField(
            model_name='touritineraryday',
            name='tour',
        ),
        migrations.DeleteModel(
            name='FAQ',
        ),
        migrations.DeleteModel(
            name='TourPhoto',
        ),
        migrations.DeleteModel(
            name='TourInclusion',
        ),
        migrations.DeleteModel(
            name='TourDate',
        ),
        migrations.DeleteModel(
            name='TourHighlight',
        ),
        migrations.DeleteModel(
            name='TourExclusion',
        ),
        migrations.DeleteModel(
            name='Tour',
        ),
        migrations.DeleteModel(
            name='TourItineraryDay',
        ),
    ]
