# Generated by Django 5.1.4 on 2025-01-18 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0004_remove_tourphoto_tour_remove_tourinclusion_tour_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Tour title (e.g. 4 Days Marrakech to Merzouga Desert Tour)', max_length=200)),
                ('description', models.TextField(help_text='Main tour description')),
                ('main_image', models.ImageField(help_text='Main header image', upload_to='tours/')),
                ('duration', models.IntegerField(help_text='Number of days')),
                ('countries', models.IntegerField(default=1, help_text='Number of countries visited')),
                ('cities', models.IntegerField(help_text='Number of cities visited')),
                ('nights', models.IntegerField(help_text='Number of nights accommodation')),
                ('breakfast_count', models.IntegerField(default=0, help_text='Total number of breakfasts')),
                ('lunch_count', models.IntegerField(default=0, help_text='Total number of lunches')),
                ('dinner_count', models.IntegerField(default=0, help_text='Total number of dinners')),
                ('activity_level', models.CharField(choices=[('easy', 'Easy'), ('moderate', 'Moderate'), ('challenging', 'Challenging')], max_length=20)),
                ('activity_description', models.TextField(help_text='Describe what the activity level includes')),
                ('solo_price', models.DecimalField(decimal_places=2, help_text='Price for solo traveler', max_digits=10)),
                ('duo_price', models.DecimalField(decimal_places=2, help_text='Price per person for 2 travelers', max_digits=10)),
                ('small_group_price', models.DecimalField(decimal_places=2, help_text='Price per person for 3-4 travelers', max_digits=10)),
                ('large_group_price', models.DecimalField(decimal_places=2, help_text='Price per person for 5+ travelers', max_digits=10)),
                ('deposit', models.DecimalField(decimal_places=2, help_text='Deposit amount', max_digits=10)),
                ('child_discount', models.IntegerField(default=25, help_text='Discount percentage for children')),
                ('map_image', models.ImageField(help_text='Tour route map', upload_to='tours/maps/')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
                ('answer', models.TextField()),
                ('order', models.IntegerField(default=0)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='app.tour')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TourDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(help_text='Tour start date')),
                ('end_date', models.DateField(help_text='Tour end date')),
                ('seats', models.IntegerField(help_text='Available seats')),
                ('is_guaranteed', models.BooleanField(default=False, help_text='Is this departure guaranteed?')),
                ('price_adjustment', models.DecimalField(decimal_places=2, default=1.0, help_text='Price multiplier for high/low season (1.00 = normal price)', max_digits=5)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dates', to='app.tour')),
            ],
            options={
                'ordering': ['start_date'],
            },
        ),
        migrations.CreateModel(
            name='TourDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.IntegerField(help_text='Day number (1, 2, 3, etc.)')),
                ('title', models.CharField(help_text='Title for this day', max_length=200)),
                ('subtitle', models.CharField(blank=True, help_text='Optional subtitle', max_length=200)),
                ('location', models.CharField(help_text='Location(s) for this day (e.g. Marrakech → Atlas Mountains)', max_length=200)),
                ('description', models.TextField(help_text="Detailed description of the day's activities")),
                ('image', models.ImageField(help_text='Main image for this day', upload_to='tours/days/')),
                ('hotel_name', models.CharField(help_text='Hotel or accommodation name', max_length=200)),
                ('hotel_link', models.URLField(blank=True, help_text='Link to hotel website (optional)')),
                ('breakfast', models.BooleanField(default=False)),
                ('lunch', models.BooleanField(default=False)),
                ('dinner', models.BooleanField(default=False)),
                ('is_welcome_day', models.BooleanField(default=False, help_text='Is this a welcome day?')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='app.tour')),
            ],
            options={
                'ordering': ['day_number'],
            },
        ),
        migrations.CreateModel(
            name='TourExclusion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="What's not included", max_length=200)),
                ('description', models.TextField(help_text="Details about why it's not included and any recommendations")),
                ('icon', models.CharField(default='fas fa-times', help_text='FontAwesome icon class', max_length=50)),
                ('order', models.IntegerField(default=0)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exclusions', to='app.tour')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TourHighlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('highlight_type', models.CharField(choices=[('visit', 'Visit'), ('discover', 'Discover'), ('see', 'See'), ('scenic_drive', 'Scenic Drive'), ('view', 'View')], help_text='Type of highlight', max_length=20)),
                ('description', models.TextField(help_text='What will travelers see/do?')),
                ('icon', models.CharField(default='fas fa-map-marker-alt', help_text='FontAwesome icon class', max_length=50)),
                ('order', models.IntegerField(default=0)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='highlights', to='app.tour')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TourInclusion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inclusion_type', models.CharField(choices=[('accommodation', 'Accommodation'), ('guide', 'Guide'), ('meals', 'Meals'), ('transport', 'Transport'), ('activities', 'Activities'), ('additional', 'Additional Services')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(help_text="Details of what's included")),
                ('icon', models.CharField(help_text='FontAwesome icon class', max_length=50)),
                ('has_dietary_options', models.BooleanField(default=False, help_text='Show dietary icons?')),
                ('order', models.IntegerField(default=0)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inclusions', to='app.tour')),
            ],
            options={
                'ordering': ['inclusion_type', 'order'],
            },
        ),
    ]
