# Generated by Django 5.1.4 on 2025-01-18 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tourexclusion',
            name='tour',
        ),
        migrations.RemoveField(
            model_name='tourdate',
            name='tour',
        ),
        migrations.RemoveField(
            model_name='tourday',
            name='tour',
        ),
        migrations.RemoveField(
            model_name='tourhighlight',
            name='tour',
        ),
        migrations.RemoveField(
            model_name='tourinclusion',
            name='tour',
        ),
        migrations.DeleteModel(
            name='FAQ',
        ),
        migrations.DeleteModel(
            name='TourExclusion',
        ),
        migrations.DeleteModel(
            name='TourDate',
        ),
        migrations.DeleteModel(
            name='TourDay',
        ),
        migrations.DeleteModel(
            name='TourHighlight',
        ),
        migrations.DeleteModel(
            name='Tour',
        ),
        migrations.DeleteModel(
            name='TourInclusion',
        ),
    ]
