# Generated by Django 5.1.4 on 2025-01-18 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_tour_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tourinclusion',
            options={'ordering': ['inclusion_type', 'order'], 'verbose_name': 'Tour Inclusion', 'verbose_name_plural': 'Tour Inclusions'},
        ),
        migrations.AddField(
            model_name='tourinclusion',
            name='icon',
            field=models.CharField(default='fas fa-check', max_length=50),
        ),
        migrations.AlterField(
            model_name='tourinclusion',
            name='description',
            field=models.TextField(help_text='Enter each item on a new line'),
        ),
        migrations.AlterField(
            model_name='tourinclusion',
            name='inclusion_type',
            field=models.CharField(choices=[('accommodation', 'Accommodation'), ('guide', 'Guide'), ('meals', 'Meals'), ('transport', 'Transport'), ('additional', 'Additional Services')], max_length=50),
        ),
        migrations.AlterField(
            model_name='tourinclusion',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
