# Generated by Django 5.1.4 on 2025-01-18 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_tourinclusion_options_tourinclusion_icon_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TourPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g., "Solo Traveler", "2 Persons", etc.', max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('per_person', models.BooleanField(default=False, help_text='Check if price is per person')),
                ('icon_class', models.CharField(help_text='FontAwesome icon class, e.g., "fas fa-user"', max_length=50)),
                ('benefits', models.TextField(help_text='Enter each benefit on a new line')),
                ('order', models.PositiveIntegerField(default=0, help_text='Order in which this price appears')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='app.tour')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
