# Generated by Django 5.1.4 on 2025-01-18 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_remove_tour_duo_price_remove_tour_large_group_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LuxuryCamp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Main title for the luxury camp', max_length=200)),
                ('subtitle', models.CharField(help_text='Subtitle describing the experience', max_length=200)),
                ('description', models.TextField(help_text='Main description of the luxury camp experience')),
                ('hero_image', models.ImageField(help_text='Hero background image', upload_to='luxury_camp/')),
                ('hero_feature_1_icon', models.CharField(default='fas fa-moon', help_text='FontAwesome icon class', max_length=50)),
                ('hero_feature_1_text', models.CharField(default='Luxury Comfort', max_length=100)),
                ('hero_feature_2_icon', models.CharField(default='fas fa-star', help_text='FontAwesome icon class', max_length=50)),
                ('hero_feature_2_text', models.CharField(default='Desert Magic', max_length=100)),
                ('hero_feature_3_icon', models.CharField(default='fas fa-compass', help_text='FontAwesome icon class', max_length=50)),
                ('hero_feature_3_text', models.CharField(default='Unique Experience', max_length=100)),
                ('duration', models.CharField(default='24 hours', help_text='Duration of the experience', max_length=50)),
                ('group_size', models.CharField(default='2-4 persons per tent', help_text='Typical group size', max_length=50)),
                ('meals_included', models.CharField(default='Dinner and breakfast included', help_text='Included meals', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LuxuryCampActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('benefits', models.TextField(help_text='Enter each benefit on a new line')),
                ('icon', models.CharField(default='fas fa-plus-circle', max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
                ('camp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_activities', to='app.luxurycamp')),
            ],
            options={
                'verbose_name_plural': 'Luxury camp activities',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='LuxuryCampExclusion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('icon', models.CharField(default='fas fa-times', max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
                ('camp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exclusions', to='app.luxurycamp')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='LuxuryCampFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
                ('answer', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('camp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='app.luxurycamp')),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='LuxuryCampInclusion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(help_text='Enter each item on a new line')),
                ('icon', models.CharField(default='fas fa-check', max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
                ('camp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inclusions', to='app.luxurycamp')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='LuxuryCampPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='luxury_camp/photos/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('camp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='app.luxurycamp')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='LuxuryCampPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g., "Private Tent", "Double Tent", etc.', max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('per_night', models.BooleanField(default=True)),
                ('icon', models.CharField(help_text='FontAwesome icon class, e.g., "fas fa-user"', max_length=50)),
                ('benefits', models.TextField(help_text='Enter each benefit on a new line')),
                ('order', models.PositiveIntegerField(default=0)),
                ('camp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='app.luxurycamp')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
