# Generated by Django 5.1.4 on 2025-01-18 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_luxurycamp_luxurycampactivity_luxurycampexclusion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='luxurycamp',
            name='slug',
            field=models.SlugField(blank=True, help_text='URL-friendly version of the title', max_length=255, unique=True),
        ),
    ]
