# Generated by Django 5.1.4 on 2025-01-18 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_luxurycamp_main_section_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='luxurycamp',
            name='main_section_image',
        ),
        migrations.RemoveField(
            model_name='luxurycamp',
            name='main_section_image_caption',
        ),
        migrations.RemoveField(
            model_name='luxurycamp',
            name='section_image_1',
        ),
        migrations.RemoveField(
            model_name='luxurycamp',
            name='section_image_1_caption',
        ),
        migrations.RemoveField(
            model_name='luxurycamp',
            name='section_image_2',
        ),
        migrations.RemoveField(
            model_name='luxurycamp',
            name='section_image_2_caption',
        ),
        migrations.RemoveField(
            model_name='luxurycamp',
            name='section_image_3',
        ),
        migrations.RemoveField(
            model_name='luxurycamp',
            name='section_image_3_caption',
        ),
    ]
