# Generated by Django 5.1.4 on 2025-01-18 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_remove_luxurycamp_main_section_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LuxuryCampExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('icon', models.CharField(default='fas fa-check', help_text='FontAwesome icon class', max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
                ('camp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='app.luxurycamp')),
            ],
            options={
                'verbose_name': 'Camp Experience',
                'verbose_name_plural': 'Camp Experiences',
                'ordering': ['order'],
            },
        ),
    ]
