# Generated by Django 5.1.4 on 2025-01-18 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_luxurycampexperience'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='luxurycampactivity',
            name='benefits',
        ),
        migrations.AlterField(
            model_name='luxurycampactivity',
            name='description',
            field=models.TextField(help_text='Enter each item on a new line'),
        ),
        migrations.AlterField(
            model_name='luxurycampexclusion',
            name='description',
            field=models.TextField(help_text='Enter each item on a new line'),
        ),
    ]
