# Generated by Django 5.1.4 on 2025-01-22 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_remove_luxurycampactivity_benefits_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TourDayOverview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.IntegerField(help_text='Day number in the tour')),
                ('title', models.CharField(help_text='Short title for this day', max_length=100)),
                ('description', models.TextField(help_text="Brief description of this day's activities")),
                ('order', models.PositiveIntegerField(default=0)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day_overviews', to='app.tour')),
            ],
            options={
                'verbose_name': 'Tour Day Overview',
                'verbose_name_plural': 'Tour Day Overviews',
                'ordering': ['order', 'day_number'],
            },
        ),
    ]
