# Generated by Django 5.1.4 on 2025-01-22 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_tourdayoverview'),
    ]

    operations = [
        migrations.AddField(
            model_name='luxurycamp',
            name='main_section_image',
            field=models.ImageField(blank=True, help_text='Main large image for the section', null=True, upload_to='luxury_camp/sections/'),
        ),
        migrations.AddField(
            model_name='luxurycamp',
            name='main_section_image_caption',
            field=models.CharField(blank=True, help_text='Caption for the main section image', max_length=200),
        ),
        migrations.AddField(
            model_name='luxurycamp',
            name='section_image_1',
            field=models.ImageField(blank=True, help_text='First small image', null=True, upload_to='luxury_camp/sections/'),
        ),
        migrations.AddField(
            model_name='luxurycamp',
            name='section_image_1_caption',
            field=models.CharField(blank=True, help_text='Caption for the first small image', max_length=200),
        ),
        migrations.AddField(
            model_name='luxurycamp',
            name='section_image_2',
            field=models.ImageField(blank=True, help_text='Second small image', null=True, upload_to='luxury_camp/sections/'),
        ),
        migrations.AddField(
            model_name='luxurycamp',
            name='section_image_2_caption',
            field=models.CharField(blank=True, help_text='Caption for the second small image', max_length=200),
        ),
        migrations.AddField(
            model_name='luxurycamp',
            name='section_image_3',
            field=models.ImageField(blank=True, help_text='Third small image', null=True, upload_to='luxury_camp/sections/'),
        ),
        migrations.AddField(
            model_name='luxurycamp',
            name='section_image_3_caption',
            field=models.CharField(blank=True, help_text='Caption for the third small image', max_length=200),
        ),
    ]
