# Generated by Django 5.1.5 on 2025-01-25 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_luxurycamp_main_section_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivitiesPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Main page title (e.g. Desert Activities)', max_length=200)),
                ('subtitle', models.CharField(help_text='Page subtitle/description', max_length=200)),
                ('hero_image', models.ImageField(help_text='Hero background image', upload_to='activities/')),
                ('meta_title', models.CharField(help_text='SEO meta title', max_length=200)),
                ('meta_description', models.TextField(help_text='SEO meta description')),
            ],
            options={
                'verbose_name': 'Activities Page',
                'verbose_name_plural': 'Activities Page',
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='activities/')),
                ('duration', models.CharField(help_text="e.g. '2 hours', '1 hour'", max_length=50)),
                ('min_group_size', models.IntegerField(help_text='Minimum group size')),
                ('max_group_size', models.IntegerField(help_text='Maximum group size')),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('moderate', 'Moderate'), ('challenging', 'Challenging'), ('all_levels', 'All Levels')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_suffix', models.CharField(default='per person', max_length=50)),
                ('detailed_description', models.TextField(help_text='Longer description for modal view')),
                ('whats_included', models.TextField(help_text='List items separated by new lines')),
                ('meeting_point', models.CharField(max_length=200)),
                ('requirements', models.TextField(help_text='List items separated by new lines')),
                ('order', models.PositiveIntegerField(default=0, help_text='Order of appearance')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Activities',
                'ordering': ['order'],
            },
        ),
    ]
