# Generated by Django 5.1.5 on 2025-01-25 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_activitiespage_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitiespage',
            name='activities_section_subtitle',
            field=models.TextField(blank=True, help_text='Text below the activities section title'),
        ),
        migrations.AddField(
            model_name='activitiespage',
            name='activities_section_title',
            field=models.CharField(default='Our Desert Activities', help_text='Title for the activities grid section', max_length=200),
        ),
        migrations.AddField(
            model_name='activitiespage',
            name='contact_text',
            field=models.TextField(blank=True, help_text='Text for contact section'),
        ),
        migrations.AddField(
            model_name='activitiespage',
            name='contact_title',
            field=models.CharField(default='Have Questions?', help_text='Title for contact section', max_length=200),
        ),
        migrations.AddField(
            model_name='activitiespage',
            name='intro_text',
            field=models.TextField(blank=True, help_text='Introduction text below the hero section'),
        ),
        migrations.AddField(
            model_name='activitiespage',
            name='meta_keywords',
            field=models.CharField(blank=True, help_text='Comma-separated keywords', max_length=500),
        ),
        migrations.AddField(
            model_name='activitiespage',
            name='show_contact_section',
            field=models.BooleanField(default=True, help_text='Show contact section at bottom of page'),
        ),
        migrations.AddField(
            model_name='activitiespage',
            name='social_description',
            field=models.TextField(blank=True, help_text='Description for social media sharing'),
        ),
        migrations.AddField(
            model_name='activitiespage',
            name='social_image',
            field=models.ImageField(blank=True, help_text='Image for social media sharing', upload_to='activities/social/'),
        ),
        migrations.AddField(
            model_name='activitiespage',
            name='social_title',
            field=models.CharField(blank=True, help_text='Title for social media sharing', max_length=200),
        ),
    ]
