# Generated by Django 5.1.5 on 2025-01-25 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_remove_activitiespage_activities_section_subtitle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='detailed_description',
            field=models.TextField(help_text='Full description of the activity for the modal view', verbose_name='Detailed Description'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='meeting_point',
            field=models.CharField(help_text='e.g. Merzouga Desert Camp reception', max_length=200, verbose_name='Meeting Point'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='requirements',
            field=models.TextField(help_text='e.g. Comfortable clothing, sunscreen, camera (optional)', verbose_name='Requirements'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='whats_included',
            field=models.TextField(help_text='Professional guide, camel ride, traditional tea ceremony, safety equipment', verbose_name="What's Included"),
        ),
    ]
