# Generated by Django 5.1.5 on 2025-01-25 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_alter_activity_detailed_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='detailed_description',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='meeting_point',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='requirements',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='whats_included',
        ),
        migrations.AlterField(
            model_name='activity',
            name='description',
            field=models.TextField(help_text='Short description for the activity card'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='duration',
            field=models.CharField(help_text="Duration (e.g. '2 hours')", max_length=50),
        ),
        migrations.AlterField(
            model_name='activity',
            name='image',
            field=models.ImageField(help_text='Activity main image', upload_to='activities/'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='max_group_size',
            field=models.IntegerField(help_text='Maximum participants'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='min_group_size',
            field=models.IntegerField(help_text='Minimum participants'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='activity',
            name='title',
            field=models.CharField(help_text='Activity title (e.g. Sunset Camel Trek)', max_length=200),
        ),
    ]
