# Generated by Django 5.1.5 on 2025-01-25 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_remove_activity_detailed_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='is_group',
            field=models.BooleanField(default=False, help_text='Check if this is a group tour'),
        ),
    ]
