# Generated by Django 5.1.5 on 2025-01-25 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_tour_is_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='luxurycamp',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Check to show this camp in navigation'),
        ),
    ]
