# Generated by Django 5.1.5 on 2025-01-26 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_luxurycamp_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='duration_hours',
            field=models.IntegerField(blank=True, help_text='Duration in hours (for day trips)', null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='is_day_trip',
            field=models.BooleanField(default=False, help_text='Check if this is a day trip'),
        ),
        migrations.AddField(
            model_name='tour',
            name='meeting_point',
            field=models.CharField(blank=True, help_text='Meeting point for day trips', max_length=200),
        ),
        migrations.AddField(
            model_name='tour',
            name='start_time',
            field=models.CharField(blank=True, help_text="Start time for day trips (e.g. '9:00 AM')", max_length=50),
        ),
    ]
