# Generated by Django 5.1.5 on 2025-01-26 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_tour_duration_hours_tour_is_day_trip_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='duration_hours',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='meeting_point',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='start_time',
        ),
        migrations.AddField(
            model_name='tour',
            name='day_trip_location',
            field=models.CharField(blank=True, help_text="Location for day trip (e.g. 'Atlas Mountains')", max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='day_trip_time',
            field=models.CharField(blank=True, help_text="Time for day trip (e.g. '9:00 AM')", max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='max_persons',
            field=models.IntegerField(blank=True, help_text='Maximum number of persons for day trip', null=True),
        ),
    ]
