# Generated by Django 5.1.5 on 2025-01-26 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_daytrip_daytripactivity_daytripcustomerphoto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='daytriphighlight',
            name='title',
        ),
        migrations.AddField(
            model_name='daytriphighlight',
            name='highlight_type',
            field=models.CharField(choices=[('visit', 'Visit'), ('discover', 'Discover'), ('see', 'See'), ('scenic_drive', 'Scenic Drive'), ('view', 'View')], default='visit', help_text='Type of highlight', max_length=20),
        ),
        migrations.AlterField(
            model_name='daytriphighlight',
            name='description',
            field=models.TextField(help_text='What will travelers see/do?'),
        ),
        migrations.AlterField(
            model_name='daytriphighlight',
            name='icon',
            field=models.CharField(default='fas fa-map-marker-alt', help_text='FontAwesome icon class', max_length=50),
        ),
    ]
