# Generated by Django 5.1.5 on 2025-01-26 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_package'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='description',
        ),
        migrations.RemoveField(
            model_name='package',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='package',
            name='group_size',
        ),
        migrations.RemoveField(
            model_name='package',
            name='image',
        ),
        migrations.RemoveField(
            model_name='package',
            name='includes_accommodation',
        ),
        migrations.RemoveField(
            model_name='package',
            name='includes_guide',
        ),
        migrations.RemoveField(
            model_name='package',
            name='includes_meals',
        ),
        migrations.RemoveField(
            model_name='package',
            name='includes_transport',
        ),
        migrations.RemoveField(
            model_name='package',
            name='is_active',
        ),
        migrations.AddField(
            model_name='package',
            name='digital_delivery',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='package',
            name='editing_hours',
            field=models.IntegerField(default=2, help_text='Hours of editing'),
        ),
        migrations.AddField(
            model_name='package',
            name='is_popular',
            field=models.BooleanField(default=False, help_text='Mark as Most Popular'),
        ),
        migrations.AddField(
            model_name='package',
            name='photo_count',
            field=models.IntegerField(default=20, help_text='Number of photos'),
        ),
        migrations.AddField(
            model_name='package',
            name='retouches',
            field=models.IntegerField(default=5, help_text='Number of retouches'),
        ),
        migrations.AlterField(
            model_name='package',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
