# Generated by Django 5.1.5 on 2025-01-26 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_remove_package_description_remove_package_duration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='is_popular',
        ),
        migrations.AddField(
            model_name='package',
            name='package_type',
            field=models.CharField(choices=[('basic', 'Basic Package'), ('standard', 'Standard Package'), ('popular', 'Most Popular'), ('premium', 'Premium Package')], default='basic', max_length=20),
        ),
    ]
