# Generated by Django 5.1.5 on 2025-01-26 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_remove_package_is_popular_package_package_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('main_image', models.ImageField(upload_to='cities/')),
                ('card_image', models.ImageField(upload_to='cities/cards/')),
                ('description', models.TextField()),
                ('hero_title', models.CharField(max_length=200)),
                ('hero_subtitle', models.TextField()),
                ('hero_image', models.ImageField(upload_to='cities/hero/')),
                ('population', models.CharField(max_length=100)),
                ('best_time', models.CharField(max_length=200)),
                ('known_for', models.TextField()),
                ('overview_title', models.CharField(max_length=200)),
                ('overview_content', models.TextField()),
                ('overview_image', models.ImageField(upload_to='cities/overview/')),
                ('weather_info', models.TextField()),
                ('best_season', models.CharField(max_length=100)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Cities',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CityAttraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='cities/attractions/')),
                ('location', models.CharField(max_length=200)),
                ('visit_time', models.CharField(max_length=100)),
                ('order', models.IntegerField(default=0)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attractions', to='app.city')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CityHighlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='cities/highlights/')),
                ('order', models.IntegerField(default=0)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='highlights', to='app.city')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
