# Generated by Django 5.1.5 on 2025-01-27 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_city_cityattraction_cityhighlight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='best_season',
        ),
        migrations.RemoveField(
            model_name='city',
            name='best_time',
        ),
        migrations.RemoveField(
            model_name='city',
            name='card_image',
        ),
        migrations.RemoveField(
            model_name='city',
            name='hero_title',
        ),
        migrations.RemoveField(
            model_name='city',
            name='known_for',
        ),
        migrations.RemoveField(
            model_name='city',
            name='main_image',
        ),
        migrations.RemoveField(
            model_name='city',
            name='overview_image',
        ),
        migrations.RemoveField(
            model_name='city',
            name='population',
        ),
        migrations.RemoveField(
            model_name='city',
            name='weather_info',
        ),
        migrations.CreateModel(
            name='CityGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='cities/gallery/')),
                ('title', models.CharField(max_length=200)),
                ('order', models.IntegerField(default=0)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='app.city')),
            ],
            options={
                'verbose_name_plural': 'City Galleries',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CityFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_type', models.CharField(choices=[('cultural', 'Cultural Heritage'), ('attractions', 'Main Attractions'), ('experiences', 'Unique Experiences')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('points', models.TextField(help_text='Enter each point on a new line')),
                ('image', models.ImageField(upload_to='cities/features/')),
                ('icon', models.CharField(default='fas fa-landmark', help_text='FontAwesome icon class', max_length=50)),
                ('order', models.IntegerField(default=0)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='app.city')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('city', 'feature_type')},
            },
        ),
    ]
