# Generated by Django 5.1.5 on 2025-01-27 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_remove_city_hero_image_remove_city_hero_subtitle_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cityfeature',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='cityfeature',
            name='city',
        ),
        migrations.RemoveField(
            model_name='cityhighlight',
            name='city',
        ),
        migrations.RemoveField(
            model_name='cityimage',
            name='city',
        ),
        migrations.AlterModelOptions(
            name='citygallery',
            options={'ordering': ['order'], 'verbose_name_plural': 'City Gallery Images'},
        ),
        migrations.RemoveField(
            model_name='city',
            name='description',
        ),
        migrations.AddField(
            model_name='city',
            name='hero_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='city',
            name='hero_image',
            field=models.ImageField(blank=True, null=True, upload_to='cities/hero/'),
        ),
        migrations.AddField(
            model_name='city',
            name='hero_title',
            field=models.CharField(default='Welcome to', max_length=200),
        ),
        migrations.AddField(
            model_name='city',
            name='overview_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='city',
            name='overview_image',
            field=models.ImageField(blank=True, null=True, upload_to='cities/overview/'),
        ),
        migrations.AddField(
            model_name='city',
            name='overview_title',
            field=models.CharField(default='About', max_length=200),
        ),
        migrations.DeleteModel(
            name='CityAttraction',
        ),
        migrations.DeleteModel(
            name='CityFeature',
        ),
        migrations.DeleteModel(
            name='CityHighlight',
        ),
        migrations.DeleteModel(
            name='CityImage',
        ),
    ]
