# Generated by Django 5.1.5 on 2025-01-27 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_alter_cityfeature_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='hero_description',
        ),
        migrations.RemoveField(
            model_name='city',
            name='hero_title',
        ),
        migrations.AddField(
            model_name='city',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
