# Generated by Django 5.1.5 on 2025-01-27 22:19

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0039_remove_city_hero_description_remove_city_hero_title_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ['order', 'title'], 'verbose_name': 'City', 'verbose_name_plural': 'Cities'},
        ),
        migrations.AlterModelOptions(
            name='citygallery',
            options={'ordering': ['order', 'created_at'], 'verbose_name': 'City Gallery Image', 'verbose_name_plural': 'City Gallery Images'},
        ),
        migrations.AddField(
            model_name='city',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='city',
            name='meta_description',
            field=models.CharField(blank=True, help_text='SEO description (max 160 characters)', max_length=160),
        ),
        migrations.AddField(
            model_name='city',
            name='meta_title',
            field=models.CharField(blank=True, help_text='SEO title (max 60 characters)', max_length=60),
        ),
        migrations.AddField(
            model_name='city',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='citygallery',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='citygallery',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Feature this image in prominent locations'),
        ),
        migrations.AlterField(
            model_name='city',
            name='description',
            field=models.TextField(blank=True, help_text='Main description that appears in the hero section'),
        ),
        migrations.AlterField(
            model_name='city',
            name='hero_image',
            field=models.ImageField(blank=True, help_text='Main image for the city (recommended: 1920x1080px)', null=True, upload_to='cities/hero/'),
        ),
        migrations.AlterField(
            model_name='city',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this city is visible on the site'),
        ),
        migrations.AlterField(
            model_name='city',
            name='order',
            field=models.IntegerField(default=0, help_text='Order of appearance (lower numbers appear first)', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='city',
            name='overview_description',
            field=models.TextField(blank=True, help_text='Detailed description about the city'),
        ),
        migrations.AlterField(
            model_name='city',
            name='overview_image',
            field=models.ImageField(blank=True, help_text='Image for the overview section (recommended: 800x600px)', null=True, upload_to='cities/overview/'),
        ),
        migrations.AlterField(
            model_name='city',
            name='overview_title',
            field=models.CharField(blank=True, default='About', help_text='Title for the overview section', max_length=200),
        ),
        migrations.AlterField(
            model_name='city',
            name='slug',
            field=models.SlugField(help_text='URL-friendly version of the city name', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='city',
            name='title',
            field=models.CharField(help_text='City name', max_length=200),
        ),
        migrations.AlterField(
            model_name='citygallery',
            name='image',
            field=models.ImageField(help_text='Gallery image (recommended: 800x800px)', upload_to='cities/gallery/'),
        ),
        migrations.AlterField(
            model_name='citygallery',
            name='order',
            field=models.IntegerField(default=0, help_text='Order of appearance in gallery', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='citygallery',
            name='title',
            field=models.CharField(help_text='Image title/caption', max_length=200),
        ),
    ]
