# Generated by Django 5.1.5 on 2025-01-28 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0040_alter_city_options_alter_citygallery_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='citygallery',
            name='city',
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='CityGallery',
        ),
    ]
