# Generated by Django 5.1.5 on 2025-01-28 22:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0041_remove_citygallery_city_delete_city_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('subtitle', models.CharField(help_text='A catchy subtitle for the city', max_length=200)),
                ('description', models.TextField(help_text='Main city description')),
                ('hero_image', models.ImageField(help_text='Hero header image', upload_to='cities/hero/')),
                ('video_url', models.URLField(blank=True, help_text='YouTube or Vimeo video URL')),
                ('population', models.CharField(blank=True, max_length=100)),
                ('area', models.CharField(blank=True, max_length=100)),
                ('climate', models.CharField(blank=True, max_length=200)),
                ('best_time_to_visit', models.CharField(max_length=200)),
                ('known_for', models.TextField(help_text='What the city is famous for')),
                ('history', models.TextField(help_text="City's historical background")),
                ('culture', models.TextField(help_text='Cultural aspects and traditions')),
                ('cuisine', models.TextField(help_text='Local food and culinary traditions')),
                ('location_description', models.TextField(help_text="Description of city's location")),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('meta_title', models.CharField(blank=True, max_length=200)),
                ('meta_description', models.TextField(blank=True)),
                ('meta_keywords', models.CharField(blank=True, max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Cities',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CityAttraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='cities/attractions/')),
                ('location', models.CharField(blank=True, max_length=200)),
                ('visit_duration', models.CharField(blank=True, max_length=100)),
                ('best_time', models.CharField(blank=True, max_length=200)),
                ('tips', models.TextField(blank=True)),
                ('order', models.IntegerField(default=0)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attractions', to='app.city')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CityGalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='cities/gallery/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='app.city')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CityHighlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('icon', models.CharField(default='fas fa-landmark', max_length=50)),
                ('image', models.ImageField(blank=True, upload_to='cities/highlights/')),
                ('order', models.IntegerField(default=0)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='highlights', to='app.city')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CityNeighborhood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='cities/neighborhoods/')),
                ('highlights', models.TextField(help_text='Key points about this neighborhood')),
                ('order', models.IntegerField(default=0)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='neighborhoods', to='app.city')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='LocalExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='cities/experiences/')),
                ('duration', models.CharField(max_length=100)),
                ('price_range', models.CharField(max_length=100)),
                ('order', models.IntegerField(default=0)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='local_experiences', to='app.city')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
