# Generated by Django 5.1.5 on 2025-01-28 22:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0042_city_cityattraction_citygalleryimage_cityhighlight_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='area',
        ),
        migrations.RemoveField(
            model_name='city',
            name='best_time_to_visit',
        ),
        migrations.RemoveField(
            model_name='city',
            name='climate',
        ),
        migrations.RemoveField(
            model_name='city',
            name='cuisine',
        ),
        migrations.RemoveField(
            model_name='city',
            name='culture',
        ),
        migrations.RemoveField(
            model_name='city',
            name='history',
        ),
        migrations.RemoveField(
            model_name='city',
            name='is_featured',
        ),
        migrations.RemoveField(
            model_name='city',
            name='known_for',
        ),
        migrations.RemoveField(
            model_name='city',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='city',
            name='location_description',
        ),
        migrations.RemoveField(
            model_name='city',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='city',
            name='meta_description',
        ),
        migrations.RemoveField(
            model_name='city',
            name='meta_keywords',
        ),
        migrations.RemoveField(
            model_name='city',
            name='meta_title',
        ),
        migrations.RemoveField(
            model_name='city',
            name='population',
        ),
        migrations.RemoveField(
            model_name='city',
            name='subtitle',
        ),
        migrations.RemoveField(
            model_name='city',
            name='video_url',
        ),
        migrations.RemoveField(
            model_name='citygalleryimage',
            name='description',
        ),
        migrations.CreateModel(
            name='CitySection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField(help_text='Section content with line breaks')),
                ('image', models.ImageField(blank=True, upload_to='cities/sections/')),
                ('order', models.IntegerField(default=0)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='app.city')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
