# Generated by Django 5.1.5 on 2025-01-29 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0044_herogridimage_photogallerycategory_photohero_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotographyPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Photography Services', max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sections', models.JSONField(default=dict, help_text='\n    Store all section content as JSON. Example format:\n    {\n        "hero": {\n            "title": "Capture Your Journey",\n            "subtitle": "Professional photography in Morocco",\n            "background_image": "path/to/image.jpg"\n        },\n        "about": {\n            "title": "About Our Services",\n            "content": "Description of services...",\n            "image": "path/to/about.jpg"\n        },\n        "gallery": {\n            "title": "Our Gallery",\n            "description": "View our work"\n        },\n        "contact": {\n            "title": "Get In Touch",\n            "content": "Contact us for bookings",\n            "button_text": "Contact Now"\n        }\n    }\n    ')),
                ('images_data', models.JSONField(default=list, help_text='\n    Store all images as JSON array. Example format:\n    [\n        {\n            "title": "Desert Sunset",\n            "description": "Sunset in Sahara",\n            "image": "path/to/image.jpg",\n            "type": "grid/gallery",\n            "order": 1,\n            "is_active": true\n        }\n    ]\n    ')),
                ('meta_title', models.CharField(blank=True, max_length=200)),
                ('meta_description', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Photography Page',
                'verbose_name_plural': 'Photography Page',
            },
        ),
        migrations.DeleteModel(
            name='HeroGridImage',
        ),
        migrations.RemoveField(
            model_name='photogallery',
            name='category',
        ),
        migrations.DeleteModel(
            name='PhotoHero',
        ),
        migrations.AlterModelOptions(
            name='package',
            options={'ordering': ['order'], 'verbose_name': 'Photography Package', 'verbose_name_plural': 'Photography Packages'},
        ),
        migrations.AddField(
            model_name='package',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='package',
            name='discount_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='image',
            field=models.ImageField(blank=True, help_text='Package display image', null=True, upload_to='packages/'),
        ),
        migrations.AddField(
            model_name='package',
            name='includes_raw_files',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='package',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='package',
            name='location_included',
            field=models.BooleanField(default=False, help_text='Whether location scouting is included'),
        ),
        migrations.AddField(
            model_name='package',
            name='turnaround_time',
            field=models.CharField(blank=True, help_text="e.g., '3-5 business days'", max_length=100),
        ),
        migrations.DeleteModel(
            name='PhotoGallery',
        ),
        migrations.DeleteModel(
            name='PhotoGalleryCategory',
        ),
    ]
