# Generated by Django 5.1.5 on 2025-01-29 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0045_photographypage_delete_herogridimage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotographyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(upload_to='photography/gallery/')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Gallery Image',
                'verbose_name_plural': 'Gallery Images',
                'ordering': ['order'],
            },
        ),
        migrations.RemoveField(
            model_name='photographypage',
            name='images_data',
        ),
        migrations.RemoveField(
            model_name='photographypage',
            name='sections',
        ),
        migrations.AddField(
            model_name='photographypage',
            name='about_content',
            field=models.TextField(blank=True, help_text='Main content for about section'),
        ),
        migrations.AddField(
            model_name='photographypage',
            name='about_image',
            field=models.ImageField(blank=True, help_text='Image for about section', null=True, upload_to='photography/about/'),
        ),
        migrations.AddField(
            model_name='photographypage',
            name='about_title',
            field=models.CharField(blank=True, help_text='Title for about section', max_length=200),
        ),
        migrations.AddField(
            model_name='photographypage',
            name='contact_button_text',
            field=models.CharField(default='Contact Now', help_text='Text to display on contact button', max_length=50),
        ),
        migrations.AddField(
            model_name='photographypage',
            name='contact_content',
            field=models.TextField(blank=True, help_text='Content for contact section'),
        ),
        migrations.AddField(
            model_name='photographypage',
            name='contact_title',
            field=models.CharField(blank=True, help_text='Title for contact section', max_length=200),
        ),
        migrations.AddField(
            model_name='photographypage',
            name='gallery_description',
            field=models.TextField(blank=True, help_text='Description for gallery section'),
        ),
        migrations.AddField(
            model_name='photographypage',
            name='gallery_title',
            field=models.CharField(blank=True, help_text='Title for gallery section', max_length=200),
        ),
        migrations.AddField(
            model_name='photographypage',
            name='hero_background',
            field=models.ImageField(blank=True, help_text='Background image for hero section', null=True, upload_to='photography/hero/'),
        ),
        migrations.AddField(
            model_name='photographypage',
            name='hero_subtitle',
            field=models.TextField(blank=True, help_text='Subtitle text below the main title'),
        ),
        migrations.AddField(
            model_name='photographypage',
            name='hero_title',
            field=models.CharField(blank=True, help_text='Main title in the hero section', max_length=200),
        ),
        migrations.AlterField(
            model_name='photographypage',
            name='meta_description',
            field=models.TextField(blank=True, help_text='Description for SEO purposes'),
        ),
        migrations.AlterField(
            model_name='photographypage',
            name='meta_title',
            field=models.CharField(blank=True, help_text='Title for SEO purposes', max_length=200),
        ),
        migrations.AddField(
            model_name='photographypage',
            name='gallery_images',
            field=models.ManyToManyField(blank=True, related_name='gallery_images', to='app.photographyimage'),
        ),
    ]
