# Generated by Django 5.1.5 on 2025-01-29 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0046_photographyimage_remove_photographypage_images_data_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Package',
        ),
        migrations.AddField(
            model_name='photographypage',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
