# Generated by Django 5.1.5 on 2025-01-29 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0047_delete_package_photographypage_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('package_type', models.CharField(choices=[('basic', 'Basic Package'), ('standard', 'Standard Package'), ('popular', 'Most Popular'), ('premium', 'Premium Package')], default='basic', max_length=20)),
                ('photo_count', models.IntegerField(default=20, help_text='Number of photos')),
                ('editing_hours', models.IntegerField(default=2, help_text='Hours of editing')),
                ('retouches', models.IntegerField(default=5, help_text='Number of retouches')),
                ('digital_delivery', models.BooleanField(default=True)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
