# Generated by Django 5.1.4 on 2025-02-01 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0049_aboutpage_alter_photographyimage_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photographypage',
            name='featured_packages',
        ),
        migrations.AddField(
            model_name='photographypage',
            name='hero_image',
            field=models.ImageField(blank=True, help_text='Main hero background image', upload_to='photography/hero/'),
        ),
    ]
