# Generated by Django 5.1.4 on 2025-02-01 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0051_photographypage_hero_image_1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photographypage',
            name='hero_image',
        ),
    ]
