# Generated by Django 5.1.4 on 2025-02-01 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0053_photographypage_hero_image_7_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='image',
            field=models.ImageField(blank=True, help_text='Package display image', upload_to='packages/'),
        ),
        migrations.AlterField(
            model_name='photographypage',
            name='hero_image_7',
            field=models.ImageField(blank=True, help_text='Hero grid image 7', upload_to='photography/hero/grid/'),
        ),
        migrations.AlterField(
            model_name='photographypage',
            name='hero_image_8',
            field=models.ImageField(blank=True, help_text='Hero grid image 8', upload_to='photography/hero/grid/'),
        ),
    ]
