# Generated by Django 5.1.4 on 2025-02-01 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0054_package_image_alter_photographypage_hero_image_7_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventGalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='events/gallery/')),
                ('location', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='EventInclusion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('icon', models.CharField(default='fas fa-check', max_length=50)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='EventPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('people', models.CharField(help_text="e.g., '1-2 persons'", max_length=50)),
                ('price', models.CharField(help_text="e.g., '340€' or 'Contact us'", max_length=50)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='EventsPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Desert Events', max_length=200)),
                ('subtitle', models.TextField(default='From intimate photoshoots to grand celebrations...')),
                ('is_active', models.BooleanField(default=True)),
                ('hero_image_1', models.ImageField(help_text='First hero slide', upload_to='events/hero/')),
                ('hero_image_2', models.ImageField(help_text='Second hero slide', upload_to='events/hero/')),
                ('hero_image_3', models.ImageField(help_text='Third hero slide', upload_to='events/hero/')),
                ('meta_title', models.CharField(blank=True, max_length=200)),
                ('meta_description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Events Page',
                'verbose_name_plural': 'Events Page',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='events/')),
                ('duration', models.CharField(help_text="e.g., 'Full Day'", max_length=50)),
                ('group_size', models.CharField(help_text="e.g., 'Custom Size'", max_length=50)),
                ('price_info', models.CharField(help_text="e.g., 'Custom Quote'", max_length=50)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('includes', models.ManyToManyField(related_name='events', to='app.eventinclusion')),
                ('prices', models.ManyToManyField(related_name='events', to='app.eventprice')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
