# Generated by Django 5.1.4 on 2025-02-01 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0055_eventgalleryimage_eventinclusion_eventprice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='app.eventspage'),
        ),
        migrations.AddField(
            model_name='event',
            name='type',
            field=models.CharField(choices=[('photography', 'Desert Photography'), ('wedding', 'Desert Wedding'), ('special', 'Special Events')], default='photography', max_length=20),
        ),
        migrations.AddField(
            model_name='eventgalleryimage',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='app.eventspage'),
        ),
    ]
