# Generated by Django 5.1.4 on 2025-02-01 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0056_event_page_event_type_eventgalleryimage_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(help_text='Main event description'),
        ),
        migrations.AlterField(
            model_name='event',
            name='duration',
            field=models.CharField(default='Full Day', help_text="e.g., 'Full Day'", max_length=50),
        ),
        migrations.AlterField(
            model_name='event',
            name='group_size',
            field=models.CharField(default='Custom Size', help_text="e.g., 'Custom Size'", max_length=50),
        ),
        migrations.AlterField(
            model_name='event',
            name='price_info',
            field=models.CharField(default='Custom Quote', help_text="e.g., 'Custom Quote'", max_length=50),
        ),
    ]
