# Generated by Django 5.1.4 on 2025-02-01 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0058_alter_event_description_alter_event_duration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='prices',
        ),
        migrations.DeleteModel(
            name='EventPrice',
        ),
        migrations.AddField(
            model_name='event',
            name='prices',
            field=models.TextField(default='1-2 persons: 340€\n3-4 persons: 440€\n5+ persons: Contact us', help_text="Enter each price on a new line (e.g., '1-2 persons: 340€')"),
        ),
    ]
