# Generated by Django 5.1.4 on 2025-02-01 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0059_remove_event_prices_delete_eventprice_event_prices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.CharField(default='Desert Photography', help_text="Enter event type (e.g., 'Desert Photography', 'Desert Wedding')", max_length=100),
        ),
    ]
