# Generated by Django 5.1.4 on 2025-02-01 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0060_alter_event_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.CharField(default='Morocco vacations travel guide', help_text='Main hero title', max_length=200)),
                ('hero_subtitle', models.TextField(default='Experience the magic of Morocco with our expert guides', help_text='Hero subtitle text')),
                ('hero_image', models.ImageField(help_text='Hero background image (1920x1080 recommended)', upload_to='home/hero/')),
                ('hero_rating', models.DecimalField(decimal_places=1, default=4.8, help_text='Rating display in hero (e.g., 4.8)', max_digits=2)),
                ('hero_button_text', models.CharField(default='See all Morocco Tours', help_text='Call to action button text', max_length=50)),
                ('things_title', models.CharField(default='Our top 5 things to do in Morocco', max_length=200)),
                ('things_subtitle', models.TextField(default='Our Morocco tour packages will show you all the iconic highlights plus the unexpected gems...')),
                ('museums_title', models.CharField(default='Best museums in Morocco', max_length=200)),
                ('museums_subtitle', models.TextField(default="When you tour Morocco with InMerzouga, we'll show you the best museums and galleries...")),
                ('food_title', models.CharField(default='Best Food in Morocco', max_length=200)),
                ('food_subtitle', models.TextField(default='Discover the rich flavors and culinary traditions of Morocco...')),
            ],
            options={
                'verbose_name': 'Home Page',
                'verbose_name_plural': 'Home Page',
            },
        ),
        migrations.CreateModel(
            name='HomeMuseum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('order', models.IntegerField(default=0)),
                ('home_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='museums', to='app.homepage')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='HomeFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('order', models.IntegerField(default=0)),
                ('home_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foods', to='app.homepage')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='HomeThingToDo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('order', models.IntegerField(default=0)),
                ('home_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='things_to_do', to='app.homepage')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
