# Generated by Django 5.1.4 on 2025-02-01 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0061_homepage_homemuseum_homefood_homethingtodo'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Food Item',
                'verbose_name_plural': 'Food Items',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='HomeSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('things', 'Things to Do'), ('museums', 'Museums'), ('food', 'Food')], help_text='Select which slider this content belongs to', max_length=20)),
                ('title', models.CharField(help_text="Section title (e.g., 'Best museums in Morocco')", max_length=200)),
                ('subtitle', models.TextField(help_text='Section subtitle/description')),
                ('slides', models.JSONField(default=list, help_text="List of slides. Each slide should have 'title' and 'description'")),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Home Page Slider',
                'verbose_name_plural': 'Home Page Sliders',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='MuseumSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Museum Item',
                'verbose_name_plural': 'Museum Items',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ThingsToDoSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Things to Do Item',
                'verbose_name_plural': 'Things to Do Items',
                'ordering': ['order'],
            },
        ),
        migrations.RemoveField(
            model_name='homefood',
            name='home_page',
        ),
        migrations.RemoveField(
            model_name='homemuseum',
            name='home_page',
        ),
        migrations.RemoveField(
            model_name='homethingtodo',
            name='home_page',
        ),
        migrations.AlterModelOptions(
            name='homepage',
            options={},
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='food_subtitle',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='food_title',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='museums_subtitle',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='museums_title',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='things_subtitle',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='things_title',
        ),
        migrations.DeleteModel(
            name='EventGalleryImage',
        ),
        migrations.DeleteModel(
            name='HomeFood',
        ),
        migrations.DeleteModel(
            name='HomeMuseum',
        ),
        migrations.DeleteModel(
            name='HomeThingToDo',
        ),
    ]
