# Generated by Django 5.1.4 on 2025-02-01 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0063_foodsection_home_page_museumsection_home_page_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='daytrip',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tour',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tour',
            name='duration',
            field=models.CharField(help_text='Number of days', max_length=50),
        ),
    ]
