# Generated by Django 5.1.4 on 2025-02-01 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0064_daytrip_order_tour_order_alter_tour_duration'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PortfolioImage',
        ),
        migrations.DeleteModel(
            name='TourDate',
        ),
    ]
