# Generated by Django 5.1.4 on 2025-02-01 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0065_delete_portfolioimage_delete_tourdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_primary', models.CharField(help_text='Primary contact number', max_length=20)),
                ('phone_secondary', models.CharField(blank=True, help_text='Secondary contact number', max_length=20)),
                ('whatsapp', models.CharField(blank=True, help_text='WhatsApp number', max_length=20)),
                ('email', models.EmailField(help_text='Contact email address', max_length=254)),
                ('address', models.TextField(help_text='Physical address')),
                ('facebook', models.URLField(blank=True, help_text='Facebook profile/page URL')),
                ('instagram', models.URLField(blank=True, help_text='Instagram profile URL')),
                ('youtube', models.URLField(blank=True, help_text='YouTube channel URL')),
                ('twitter', models.URLField(blank=True, help_text='Twitter profile URL')),
                ('tiktok', models.URLField(blank=True, help_text='TikTok profile URL')),
                ('business_hours', models.TextField(blank=True, help_text="Business hours (e.g., 'Mon-Fri: 9AM-6PM')")),
                ('additional_info', models.TextField(blank=True, help_text='Any additional contact information')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Contact Information',
                'verbose_name_plural': 'Contact Information',
            },
        ),
    ]
