# Generated by Django 5.1.4 on 2025-02-01 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0066_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='additional_info',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='address',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='business_hours',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='phone_primary',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='phone_secondary',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='tiktok',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='twitter',
        ),
        migrations.AddField(
            model_name='contact',
            name='phone',
            field=models.CharField(blank=True, help_text='Main contact number', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(blank=True, help_text='Contact email address', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='instagram',
            field=models.URLField(blank=True, help_text='Instagram profile URL', null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='whatsapp',
            field=models.CharField(blank=True, help_text='WhatsApp number (include country code)', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='youtube',
            field=models.URLField(blank=True, help_text='YouTube channel URL', null=True),
        ),
    ]
