# Generated by Django 5.1.4 on 2025-02-01 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0067_remove_contact_additional_info_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Promo title (e.g. 'Special Offer!')", max_length=100)),
                ('discount', models.IntegerField(help_text='Discount percentage (e.g. 20 for 20% off)')),
                ('image', models.ImageField(help_text='Promotional image', upload_to='promos/')),
                ('link', models.URLField(help_text='Link to the tour or page being promoted')),
                ('feature1_icon', models.CharField(help_text="FontAwesome icon class (e.g. 'fa-campground')", max_length=50)),
                ('feature1_text', models.CharField(max_length=100)),
                ('feature2_icon', models.CharField(max_length=50)),
                ('feature2_text', models.CharField(max_length=100)),
                ('feature3_icon', models.CharField(max_length=50)),
                ('feature3_text', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=False)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Promotion',
                'verbose_name_plural': 'Promotions',
            },
        ),
    ]
