# Generated by Django 5.1.4 on 2025-02-01 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0068_promo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promo',
            name='feature1_icon',
        ),
        migrations.RemoveField(
            model_name='promo',
            name='feature2_icon',
        ),
        migrations.RemoveField(
            model_name='promo',
            name='feature3_icon',
        ),
    ]
