# Generated by Django 5.1.5 on 2025-02-18 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0069_remove_promo_feature1_icon_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutpage',
            options={'verbose_name': 'A - About Page', 'verbose_name_plural': 'A - About Page'},
        ),
        migrations.AlterModelOptions(
            name='activitiespage',
            options={'verbose_name': 'A - Activities Page', 'verbose_name_plural': 'A - Activities Page'},
        ),
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ['order'], 'verbose_name': 'C - Activity', 'verbose_name_plural': 'C - Activities'},
        ),
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ['order'], 'verbose_name': 'C - City', 'verbose_name_plural': 'C - Cities'},
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'F - Contact Information', 'verbose_name_plural': 'F - Contact Information'},
        ),
        migrations.AlterModelOptions(
            name='daytrip',
            options={'ordering': ['order'], 'verbose_name': 'B - Day Trip', 'verbose_name_plural': 'B - Day Trips'},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['order'], 'verbose_name': 'E - Event', 'verbose_name_plural': 'E - Events'},
        ),
        migrations.AlterModelOptions(
            name='eventspage',
            options={'verbose_name': 'A - Events Page', 'verbose_name_plural': 'A - Events Page'},
        ),
        migrations.AlterModelOptions(
            name='homepage',
            options={'verbose_name': 'A - Home Page', 'verbose_name_plural': 'A - Home Page'},
        ),
        migrations.AlterModelOptions(
            name='luxurycamp',
            options={'verbose_name': 'D - Luxury Camp', 'verbose_name_plural': 'D - Luxury Camps'},
        ),
        migrations.AlterModelOptions(
            name='package',
            options={'ordering': ['order'], 'verbose_name': 'E - Package', 'verbose_name_plural': 'E - Packages'},
        ),
        migrations.AlterModelOptions(
            name='photographypage',
            options={'verbose_name': 'A - Photography Page', 'verbose_name_plural': 'A - Photography Page'},
        ),
        migrations.AlterModelOptions(
            name='promo',
            options={'verbose_name': 'F - Promotion', 'verbose_name_plural': 'F - Promotions'},
        ),
        migrations.AlterModelOptions(
            name='tour',
            options={'verbose_name': 'B - Tour', 'verbose_name_plural': 'B - Tours'},
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='canonical_url',
            field=models.URLField(blank=True, help_text='Canonical URL if different from current URL'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='meta_description',
            field=models.TextField(blank=True, help_text='SEO meta description (recommended: 150-160 characters)'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='meta_keywords',
            field=models.CharField(blank=True, help_text='Comma-separated keywords', max_length=500),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='meta_title',
            field=models.CharField(blank=True, help_text='SEO meta title (max 200 characters)', max_length=200),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='og_description',
            field=models.TextField(blank=True, help_text='Open Graph description for social sharing'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='og_image',
            field=models.ImageField(blank=True, help_text='Open Graph image (1200x630 recommended)', upload_to='seo/'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='og_title',
            field=models.CharField(blank=True, help_text='Open Graph title for social sharing', max_length=200),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='robots_follow',
            field=models.BooleanField(default=True, help_text='Allow search engines to follow links on this page'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='robots_index',
            field=models.BooleanField(default=True, help_text='Allow search engines to index this page'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='structured_data',
            field=models.JSONField(blank=True, help_text='JSON-LD structured data', null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='canonical_url',
            field=models.URLField(blank=True, help_text='Canonical URL if different from current URL'),
        ),
        migrations.AddField(
            model_name='city',
            name='meta_description',
            field=models.TextField(blank=True, help_text='SEO meta description (recommended: 150-160 characters)'),
        ),
        migrations.AddField(
            model_name='city',
            name='meta_keywords',
            field=models.CharField(blank=True, help_text='Comma-separated keywords', max_length=500),
        ),
        migrations.AddField(
            model_name='city',
            name='meta_title',
            field=models.CharField(blank=True, help_text='SEO meta title (max 200 characters)', max_length=200),
        ),
        migrations.AddField(
            model_name='city',
            name='og_description',
            field=models.TextField(blank=True, help_text='Open Graph description for social sharing'),
        ),
        migrations.AddField(
            model_name='city',
            name='og_image',
            field=models.ImageField(blank=True, help_text='Open Graph image (1200x630 recommended)', upload_to='seo/'),
        ),
        migrations.AddField(
            model_name='city',
            name='og_title',
            field=models.CharField(blank=True, help_text='Open Graph title for social sharing', max_length=200),
        ),
        migrations.AddField(
            model_name='city',
            name='robots_follow',
            field=models.BooleanField(default=True, help_text='Allow search engines to follow links on this page'),
        ),
        migrations.AddField(
            model_name='city',
            name='robots_index',
            field=models.BooleanField(default=True, help_text='Allow search engines to index this page'),
        ),
        migrations.AddField(
            model_name='city',
            name='structured_data',
            field=models.JSONField(blank=True, help_text='JSON-LD structured data', null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='canonical_url',
            field=models.URLField(blank=True, help_text='Canonical URL if different from current URL'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='meta_description',
            field=models.TextField(blank=True, help_text='SEO meta description (recommended: 150-160 characters)'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='meta_keywords',
            field=models.CharField(blank=True, help_text='Comma-separated keywords', max_length=500),
        ),
        migrations.AddField(
            model_name='homepage',
            name='meta_title',
            field=models.CharField(blank=True, help_text='SEO meta title (max 200 characters)', max_length=200),
        ),
        migrations.AddField(
            model_name='homepage',
            name='og_description',
            field=models.TextField(blank=True, help_text='Open Graph description for social sharing'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='og_image',
            field=models.ImageField(blank=True, help_text='Open Graph image (1200x630 recommended)', upload_to='seo/'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='og_title',
            field=models.CharField(blank=True, help_text='Open Graph title for social sharing', max_length=200),
        ),
        migrations.AddField(
            model_name='homepage',
            name='robots_follow',
            field=models.BooleanField(default=True, help_text='Allow search engines to follow links on this page'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='robots_index',
            field=models.BooleanField(default=True, help_text='Allow search engines to index this page'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='structured_data',
            field=models.JSONField(blank=True, help_text='JSON-LD structured data', null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='canonical_url',
            field=models.URLField(blank=True, help_text='Canonical URL if different from current URL'),
        ),
        migrations.AddField(
            model_name='tour',
            name='meta_description',
            field=models.TextField(blank=True, help_text='SEO meta description (recommended: 150-160 characters)'),
        ),
        migrations.AddField(
            model_name='tour',
            name='meta_keywords',
            field=models.CharField(blank=True, help_text='Comma-separated keywords', max_length=500),
        ),
        migrations.AddField(
            model_name='tour',
            name='meta_title',
            field=models.CharField(blank=True, help_text='SEO meta title (max 200 characters)', max_length=200),
        ),
        migrations.AddField(
            model_name='tour',
            name='og_description',
            field=models.TextField(blank=True, help_text='Open Graph description for social sharing'),
        ),
        migrations.AddField(
            model_name='tour',
            name='og_image',
            field=models.ImageField(blank=True, help_text='Open Graph image (1200x630 recommended)', upload_to='seo/'),
        ),
        migrations.AddField(
            model_name='tour',
            name='og_title',
            field=models.CharField(blank=True, help_text='Open Graph title for social sharing', max_length=200),
        ),
        migrations.AddField(
            model_name='tour',
            name='robots_follow',
            field=models.BooleanField(default=True, help_text='Allow search engines to follow links on this page'),
        ),
        migrations.AddField(
            model_name='tour',
            name='robots_index',
            field=models.BooleanField(default=True, help_text='Allow search engines to index this page'),
        ),
        migrations.AddField(
            model_name='tour',
            name='structured_data',
            field=models.JSONField(blank=True, help_text='JSON-LD structured data', null=True),
        ),
    ]
