# Generated by Django 5.1.5 on 2025-02-18 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0070_alter_aboutpage_options_alter_activitiespage_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutpage',
            name='canonical_url',
            field=models.URLField(blank=True, help_text='Canonical URL if different from current URL', null=True),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='meta_description',
            field=models.TextField(blank=True, help_text='SEO meta description (recommended: 150-160 characters)', null=True),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='meta_keywords',
            field=models.CharField(blank=True, help_text='Comma-separated keywords', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='meta_title',
            field=models.CharField(blank=True, help_text='SEO meta title (max 200 characters)', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='og_description',
            field=models.TextField(blank=True, help_text='Open Graph description for social sharing', null=True),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='og_image',
            field=models.ImageField(blank=True, help_text='Open Graph image (1200x630 recommended)', null=True, upload_to='seo/'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='og_title',
            field=models.CharField(blank=True, help_text='Open Graph title for social sharing', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='robots_follow',
            field=models.BooleanField(default=True, help_text='Allow search engines to follow links on this page', null=True),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='robots_index',
            field=models.BooleanField(default=True, help_text='Allow search engines to index this page', null=True),
        ),
        migrations.AlterField(
            model_name='city',
            name='canonical_url',
            field=models.URLField(blank=True, help_text='Canonical URL if different from current URL', null=True),
        ),
        migrations.AlterField(
            model_name='city',
            name='meta_description',
            field=models.TextField(blank=True, help_text='SEO meta description (recommended: 150-160 characters)', null=True),
        ),
        migrations.AlterField(
            model_name='city',
            name='meta_keywords',
            field=models.CharField(blank=True, help_text='Comma-separated keywords', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='city',
            name='meta_title',
            field=models.CharField(blank=True, help_text='SEO meta title (max 200 characters)', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='city',
            name='og_description',
            field=models.TextField(blank=True, help_text='Open Graph description for social sharing', null=True),
        ),
        migrations.AlterField(
            model_name='city',
            name='og_image',
            field=models.ImageField(blank=True, help_text='Open Graph image (1200x630 recommended)', null=True, upload_to='seo/'),
        ),
        migrations.AlterField(
            model_name='city',
            name='og_title',
            field=models.CharField(blank=True, help_text='Open Graph title for social sharing', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='city',
            name='robots_follow',
            field=models.BooleanField(default=True, help_text='Allow search engines to follow links on this page', null=True),
        ),
        migrations.AlterField(
            model_name='city',
            name='robots_index',
            field=models.BooleanField(default=True, help_text='Allow search engines to index this page', null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='canonical_url',
            field=models.URLField(blank=True, help_text='Canonical URL if different from current URL', null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='meta_description',
            field=models.TextField(blank=True, help_text='SEO meta description (recommended: 150-160 characters)', null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='meta_keywords',
            field=models.CharField(blank=True, help_text='Comma-separated keywords', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='meta_title',
            field=models.CharField(blank=True, help_text='SEO meta title (max 200 characters)', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='og_description',
            field=models.TextField(blank=True, help_text='Open Graph description for social sharing', null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='og_image',
            field=models.ImageField(blank=True, help_text='Open Graph image (1200x630 recommended)', null=True, upload_to='seo/'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='og_title',
            field=models.CharField(blank=True, help_text='Open Graph title for social sharing', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='robots_follow',
            field=models.BooleanField(default=True, help_text='Allow search engines to follow links on this page', null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='robots_index',
            field=models.BooleanField(default=True, help_text='Allow search engines to index this page', null=True),
        ),
        migrations.AlterField(
            model_name='tour',
            name='canonical_url',
            field=models.URLField(blank=True, help_text='Canonical URL if different from current URL', null=True),
        ),
        migrations.AlterField(
            model_name='tour',
            name='meta_description',
            field=models.TextField(blank=True, help_text='SEO meta description (recommended: 150-160 characters)', null=True),
        ),
        migrations.AlterField(
            model_name='tour',
            name='meta_keywords',
            field=models.CharField(blank=True, help_text='Comma-separated keywords', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='tour',
            name='meta_title',
            field=models.CharField(blank=True, help_text='SEO meta title (max 200 characters)', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='tour',
            name='og_description',
            field=models.TextField(blank=True, help_text='Open Graph description for social sharing', null=True),
        ),
        migrations.AlterField(
            model_name='tour',
            name='og_image',
            field=models.ImageField(blank=True, help_text='Open Graph image (1200x630 recommended)', null=True, upload_to='seo/'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='og_title',
            field=models.CharField(blank=True, help_text='Open Graph title for social sharing', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='tour',
            name='robots_follow',
            field=models.BooleanField(default=True, help_text='Allow search engines to follow links on this page', null=True),
        ),
        migrations.AlterField(
            model_name='tour',
            name='robots_index',
            field=models.BooleanField(default=True, help_text='Allow search engines to index this page', null=True),
        ),
    ]
