# Generated by Django 5.1.5 on 2025-02-18 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0071_alter_aboutpage_canonical_url_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photographypage',
            options={'verbose_name': 'D - Photography Page', 'verbose_name_plural': 'D - Photography Page'},
        ),
        migrations.RemoveField(
            model_name='photographypage',
            name='created_at',
        ),
        migrations.AddField(
            model_name='photographypage',
            name='canonical_url',
            field=models.URLField(blank=True, help_text='Canonical URL if different from current URL', null=True),
        ),
        migrations.AddField(
            model_name='photographypage',
            name='meta_keywords',
            field=models.CharField(blank=True, help_text='Comma-separated keywords', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='photographypage',
            name='og_description',
            field=models.TextField(blank=True, help_text='Open Graph description for social sharing', null=True),
        ),
        migrations.AddField(
            model_name='photographypage',
            name='og_image',
            field=models.ImageField(blank=True, help_text='Open Graph image (1200x630 recommended)', null=True, upload_to='seo/'),
        ),
        migrations.AddField(
            model_name='photographypage',
            name='og_title',
            field=models.CharField(blank=True, help_text='Open Graph title for social sharing', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='photographypage',
            name='robots_follow',
            field=models.BooleanField(default=True, help_text='Allow search engines to follow links on this page', null=True),
        ),
        migrations.AddField(
            model_name='photographypage',
            name='robots_index',
            field=models.BooleanField(default=True, help_text='Allow search engines to index this page', null=True),
        ),
        migrations.AddField(
            model_name='photographypage',
            name='structured_data',
            field=models.JSONField(blank=True, help_text='JSON-LD structured data', null=True),
        ),
        migrations.AlterField(
            model_name='photographyimage',
            name='category',
            field=models.CharField(blank=True, choices=[('landscape', 'Landscape'), ('portrait', 'Portrait'), ('street', 'Street'), ('architecture', 'Architecture'), ('culture', 'Culture & Traditions')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='photographypage',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='photographypage',
            name='hero_image_1',
            field=models.ImageField(upload_to='photography/hero/'),
        ),
        migrations.AlterField(
            model_name='photographypage',
            name='hero_image_2',
            field=models.ImageField(upload_to='photography/hero/'),
        ),
        migrations.AlterField(
            model_name='photographypage',
            name='hero_image_3',
            field=models.ImageField(upload_to='photography/hero/'),
        ),
        migrations.AlterField(
            model_name='photographypage',
            name='hero_image_4',
            field=models.ImageField(upload_to='photography/hero/'),
        ),
        migrations.AlterField(
            model_name='photographypage',
            name='hero_image_5',
            field=models.ImageField(upload_to='photography/hero/'),
        ),
        migrations.AlterField(
            model_name='photographypage',
            name='hero_image_6',
            field=models.ImageField(upload_to='photography/hero/'),
        ),
        migrations.AlterField(
            model_name='photographypage',
            name='hero_image_7',
            field=models.ImageField(upload_to='photography/hero/'),
        ),
        migrations.AlterField(
            model_name='photographypage',
            name='hero_image_8',
            field=models.ImageField(upload_to='photography/hero/'),
        ),
        migrations.AlterField(
            model_name='photographypage',
            name='hero_subtitle',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='photographypage',
            name='hero_title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='photographypage',
            name='meta_description',
            field=models.TextField(blank=True, help_text='SEO meta description (recommended: 150-160 characters)', null=True),
        ),
        migrations.AlterField(
            model_name='photographypage',
            name='meta_title',
            field=models.CharField(blank=True, help_text='SEO meta title (max 200 characters)', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='photographypage',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
