# Generated by Django 5.1.5 on 2025-02-20 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0072_alter_photographypage_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photographypage',
            options={'verbose_name': 'A - Photography Page', 'verbose_name_plural': 'A - Photography Page'},
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='canonical_url',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='meta_description',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='meta_keywords',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='meta_title',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='og_description',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='og_image',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='og_title',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='robots_follow',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='robots_index',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='structured_data',
        ),
        migrations.RemoveField(
            model_name='city',
            name='canonical_url',
        ),
        migrations.RemoveField(
            model_name='city',
            name='meta_description',
        ),
        migrations.RemoveField(
            model_name='city',
            name='meta_keywords',
        ),
        migrations.RemoveField(
            model_name='city',
            name='meta_title',
        ),
        migrations.RemoveField(
            model_name='city',
            name='og_description',
        ),
        migrations.RemoveField(
            model_name='city',
            name='og_image',
        ),
        migrations.RemoveField(
            model_name='city',
            name='og_title',
        ),
        migrations.RemoveField(
            model_name='city',
            name='robots_follow',
        ),
        migrations.RemoveField(
            model_name='city',
            name='robots_index',
        ),
        migrations.RemoveField(
            model_name='city',
            name='structured_data',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='structured_data',
        ),
        migrations.RemoveField(
            model_name='photographypage',
            name='canonical_url',
        ),
        migrations.RemoveField(
            model_name='photographypage',
            name='meta_description',
        ),
        migrations.RemoveField(
            model_name='photographypage',
            name='meta_keywords',
        ),
        migrations.RemoveField(
            model_name='photographypage',
            name='meta_title',
        ),
        migrations.RemoveField(
            model_name='photographypage',
            name='og_description',
        ),
        migrations.RemoveField(
            model_name='photographypage',
            name='og_image',
        ),
        migrations.RemoveField(
            model_name='photographypage',
            name='og_title',
        ),
        migrations.RemoveField(
            model_name='photographypage',
            name='robots_follow',
        ),
        migrations.RemoveField(
            model_name='photographypage',
            name='robots_index',
        ),
        migrations.RemoveField(
            model_name='photographypage',
            name='structured_data',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='canonical_url',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='meta_description',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='meta_keywords',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='meta_title',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='og_description',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='og_image',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='og_title',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='robots_follow',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='robots_index',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='structured_data',
        ),
        migrations.AddField(
            model_name='homepage',
            name='custom_meta_tags',
            field=models.TextField(blank=True, help_text='Additional meta tags (one per line, format: name|content)', null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='og_type',
            field=models.CharField(blank=True, default='website', help_text='Open Graph type (e.g., website, article)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='schema_markup',
            field=models.JSONField(blank=True, help_text='JSON-LD schema markup', null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='sitemap_changefreq',
            field=models.CharField(blank=True, help_text='Sitemap change frequency (e.g., daily, weekly)', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='sitemap_priority',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Sitemap priority (0.0 to 1.0)', max_digits=2, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='twitter_card',
            field=models.CharField(blank=True, default='summary_large_image', help_text='Twitter card type (summary, summary_large_image)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='twitter_description',
            field=models.CharField(blank=True, help_text='Twitter card description (falls back to OG description)', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='twitter_image',
            field=models.ImageField(blank=True, help_text='Twitter card image (falls back to OG image)', null=True, upload_to='seo/twitter/'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='twitter_title',
            field=models.CharField(blank=True, help_text='Twitter card title (falls back to OG title)', max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='photographypage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='canonical_url',
            field=models.URLField(blank=True, help_text='Canonical URL (if different from current URL)', null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='hero_subtitle',
            field=models.TextField(help_text='Hero subtitle text'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='hero_title',
            field=models.CharField(help_text='Main hero title', max_length=200),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='meta_description',
            field=models.CharField(blank=True, help_text='Meta description (150-160 characters recommended)', max_length=160, null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='meta_keywords',
            field=models.CharField(blank=True, help_text='Comma-separated keywords', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='meta_title',
            field=models.CharField(blank=True, help_text='Meta title (50-60 characters recommended)', max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='og_description',
            field=models.CharField(blank=True, help_text='Open Graph description for social media', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='og_image',
            field=models.ImageField(blank=True, help_text='Open Graph image (1200x630px recommended)', null=True, upload_to='seo/og/'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='og_title',
            field=models.CharField(blank=True, help_text='Open Graph title for social media', max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='photographyimage',
            name='category',
            field=models.CharField(blank=True, choices=[('landscape', 'Landscape'), ('portrait', 'Portrait'), ('culture', 'Culture'), ('events', 'Events')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='photographypage',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='photographypage',
            name='hero_image_1',
            field=models.ImageField(blank=True, help_text='Hero grid image 1', upload_to='photography/hero/grid/'),
        ),
        migrations.AlterField(
            model_name='photographypage',
            name='hero_image_2',
            field=models.ImageField(blank=True, help_text='Hero grid image 2', upload_to='photography/hero/grid/'),
        ),
        migrations.AlterField(
            model_name='photographypage',
            name='hero_image_3',
            field=models.ImageField(blank=True, help_text='Hero grid image 3', upload_to='photography/hero/grid/'),
        ),
        migrations.AlterField(
            model_name='photographypage',
            name='hero_image_4',
            field=models.ImageField(blank=True, help_text='Hero grid image 4', upload_to='photography/hero/grid/'),
        ),
        migrations.AlterField(
            model_name='photographypage',
            name='hero_image_5',
            field=models.ImageField(blank=True, help_text='Hero grid image 5', upload_to='photography/hero/grid/'),
        ),
        migrations.AlterField(
            model_name='photographypage',
            name='hero_image_6',
            field=models.ImageField(blank=True, help_text='Hero grid image 6', upload_to='photography/hero/grid/'),
        ),
        migrations.AlterField(
            model_name='photographypage',
            name='hero_image_7',
            field=models.ImageField(blank=True, help_text='Hero grid image 7', upload_to='photography/hero/grid/'),
        ),
        migrations.AlterField(
            model_name='photographypage',
            name='hero_image_8',
            field=models.ImageField(blank=True, help_text='Hero grid image 8', upload_to='photography/hero/grid/'),
        ),
        migrations.AlterField(
            model_name='photographypage',
            name='hero_subtitle',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='photographypage',
            name='hero_title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='photographypage',
            name='title',
            field=models.CharField(default='Photography Services', max_length=200),
        ),
    ]
