# Generated by Django 5.1.5 on 2025-02-20 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0074_remove_homepage_schema_markup_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='custom_meta_tags',
        ),
    ]
