# Generated by Django 5.1.5 on 2025-02-20 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0076_photographypage_canonical_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpage',
            name='canonical_url',
            field=models.URLField(blank=True, help_text='Canonical URL (if different from current URL)', null=True),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='meta_description',
            field=models.CharField(blank=True, help_text='Meta description (150-160 characters recommended)', max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='meta_keywords',
            field=models.CharField(blank=True, help_text='Comma-separated keywords', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='meta_title',
            field=models.CharField(blank=True, help_text='Meta title (50-60 characters recommended)', max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='og_description',
            field=models.CharField(blank=True, help_text='Open Graph description for social media', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='og_image',
            field=models.ImageField(blank=True, help_text='Open Graph image (1200x630px recommended)', null=True, upload_to='seo/og/'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='og_title',
            field=models.CharField(blank=True, help_text='Open Graph title for social media', max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='og_type',
            field=models.CharField(blank=True, default='website', help_text='Open Graph type (e.g., website, article)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='robots_follow',
            field=models.BooleanField(default=True, help_text='Allow search engines to follow links on this page', null=True),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='robots_index',
            field=models.BooleanField(default=True, help_text='Allow search engines to index this page', null=True),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='twitter_card',
            field=models.CharField(blank=True, default='summary_large_image', help_text='Twitter card type (summary, summary_large_image)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='twitter_description',
            field=models.CharField(blank=True, help_text='Twitter card description (falls back to OG description)', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='twitter_image',
            field=models.ImageField(blank=True, help_text='Twitter card image (falls back to OG image)', null=True, upload_to='seo/twitter/'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='twitter_title',
            field=models.CharField(blank=True, help_text='Twitter card title (falls back to OG title)', max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='activitiespage',
            name='canonical_url',
            field=models.URLField(blank=True, help_text='Canonical URL (if different from current URL)', null=True),
        ),
        migrations.AddField(
            model_name='activitiespage',
            name='og_description',
            field=models.CharField(blank=True, help_text='Open Graph description for social media', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='activitiespage',
            name='og_image',
            field=models.ImageField(blank=True, help_text='Open Graph image (1200x630px recommended)', null=True, upload_to='seo/og/'),
        ),
        migrations.AddField(
            model_name='activitiespage',
            name='og_title',
            field=models.CharField(blank=True, help_text='Open Graph title for social media', max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='activitiespage',
            name='og_type',
            field=models.CharField(blank=True, default='website', help_text='Open Graph type (e.g., website, article)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='activitiespage',
            name='robots_follow',
            field=models.BooleanField(default=True, help_text='Allow search engines to follow links on this page', null=True),
        ),
        migrations.AddField(
            model_name='activitiespage',
            name='robots_index',
            field=models.BooleanField(default=True, help_text='Allow search engines to index this page', null=True),
        ),
        migrations.AddField(
            model_name='activitiespage',
            name='twitter_card',
            field=models.CharField(blank=True, default='summary_large_image', help_text='Twitter card type (summary, summary_large_image)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='activitiespage',
            name='twitter_description',
            field=models.CharField(blank=True, help_text='Twitter card description (falls back to OG description)', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='activitiespage',
            name='twitter_image',
            field=models.ImageField(blank=True, help_text='Twitter card image (falls back to OG image)', null=True, upload_to='seo/twitter/'),
        ),
        migrations.AddField(
            model_name='activitiespage',
            name='twitter_title',
            field=models.CharField(blank=True, help_text='Twitter card title (falls back to OG title)', max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='canonical_url',
            field=models.URLField(blank=True, help_text='Canonical URL (if different from current URL)', null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='meta_description',
            field=models.CharField(blank=True, help_text='Meta description (150-160 characters recommended)', max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='meta_keywords',
            field=models.CharField(blank=True, help_text='Comma-separated keywords', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='meta_title',
            field=models.CharField(blank=True, help_text='Meta title (50-60 characters recommended)', max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='og_description',
            field=models.CharField(blank=True, help_text='Open Graph description for social media', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='og_image',
            field=models.ImageField(blank=True, help_text='Open Graph image (1200x630px recommended)', null=True, upload_to='seo/og/'),
        ),
        migrations.AddField(
            model_name='city',
            name='og_title',
            field=models.CharField(blank=True, help_text='Open Graph title for social media', max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='og_type',
            field=models.CharField(blank=True, default='website', help_text='Open Graph type (e.g., website, article)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='robots_follow',
            field=models.BooleanField(default=True, help_text='Allow search engines to follow links on this page', null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='robots_index',
            field=models.BooleanField(default=True, help_text='Allow search engines to index this page', null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='twitter_card',
            field=models.CharField(blank=True, default='summary_large_image', help_text='Twitter card type (summary, summary_large_image)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='twitter_description',
            field=models.CharField(blank=True, help_text='Twitter card description (falls back to OG description)', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='twitter_image',
            field=models.ImageField(blank=True, help_text='Twitter card image (falls back to OG image)', null=True, upload_to='seo/twitter/'),
        ),
        migrations.AddField(
            model_name='city',
            name='twitter_title',
            field=models.CharField(blank=True, help_text='Twitter card title (falls back to OG title)', max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='canonical_url',
            field=models.URLField(blank=True, help_text='Canonical URL (if different from current URL)', null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='meta_description',
            field=models.CharField(blank=True, help_text='Meta description (150-160 characters recommended)', max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='meta_keywords',
            field=models.CharField(blank=True, help_text='Comma-separated keywords', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='meta_title',
            field=models.CharField(blank=True, help_text='Meta title (50-60 characters recommended)', max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='og_description',
            field=models.CharField(blank=True, help_text='Open Graph description for social media', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='og_image',
            field=models.ImageField(blank=True, help_text='Open Graph image (1200x630px recommended)', null=True, upload_to='seo/og/'),
        ),
        migrations.AddField(
            model_name='contact',
            name='og_title',
            field=models.CharField(blank=True, help_text='Open Graph title for social media', max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='og_type',
            field=models.CharField(blank=True, default='website', help_text='Open Graph type (e.g., website, article)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='robots_follow',
            field=models.BooleanField(default=True, help_text='Allow search engines to follow links on this page', null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='robots_index',
            field=models.BooleanField(default=True, help_text='Allow search engines to index this page', null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='twitter_card',
            field=models.CharField(blank=True, default='summary_large_image', help_text='Twitter card type (summary, summary_large_image)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='twitter_description',
            field=models.CharField(blank=True, help_text='Twitter card description (falls back to OG description)', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='twitter_image',
            field=models.ImageField(blank=True, help_text='Twitter card image (falls back to OG image)', null=True, upload_to='seo/twitter/'),
        ),
        migrations.AddField(
            model_name='contact',
            name='twitter_title',
            field=models.CharField(blank=True, help_text='Twitter card title (falls back to OG title)', max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='daytrip',
            name='canonical_url',
            field=models.URLField(blank=True, help_text='Canonical URL (if different from current URL)', null=True),
        ),
        migrations.AddField(
            model_name='daytrip',
            name='meta_description',
            field=models.CharField(blank=True, help_text='Meta description (150-160 characters recommended)', max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='daytrip',
            name='meta_keywords',
            field=models.CharField(blank=True, help_text='Comma-separated keywords', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='daytrip',
            name='meta_title',
            field=models.CharField(blank=True, help_text='Meta title (50-60 characters recommended)', max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='daytrip',
            name='og_description',
            field=models.CharField(blank=True, help_text='Open Graph description for social media', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='daytrip',
            name='og_image',
            field=models.ImageField(blank=True, help_text='Open Graph image (1200x630px recommended)', null=True, upload_to='seo/og/'),
        ),
        migrations.AddField(
            model_name='daytrip',
            name='og_title',
            field=models.CharField(blank=True, help_text='Open Graph title for social media', max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='daytrip',
            name='og_type',
            field=models.CharField(blank=True, default='website', help_text='Open Graph type (e.g., website, article)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='daytrip',
            name='robots_follow',
            field=models.BooleanField(default=True, help_text='Allow search engines to follow links on this page', null=True),
        ),
        migrations.AddField(
            model_name='daytrip',
            name='robots_index',
            field=models.BooleanField(default=True, help_text='Allow search engines to index this page', null=True),
        ),
        migrations.AddField(
            model_name='daytrip',
            name='twitter_card',
            field=models.CharField(blank=True, default='summary_large_image', help_text='Twitter card type (summary, summary_large_image)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='daytrip',
            name='twitter_description',
            field=models.CharField(blank=True, help_text='Twitter card description (falls back to OG description)', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='daytrip',
            name='twitter_image',
            field=models.ImageField(blank=True, help_text='Twitter card image (falls back to OG image)', null=True, upload_to='seo/twitter/'),
        ),
        migrations.AddField(
            model_name='daytrip',
            name='twitter_title',
            field=models.CharField(blank=True, help_text='Twitter card title (falls back to OG title)', max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='eventspage',
            name='canonical_url',
            field=models.URLField(blank=True, help_text='Canonical URL (if different from current URL)', null=True),
        ),
        migrations.AddField(
            model_name='eventspage',
            name='meta_keywords',
            field=models.CharField(blank=True, help_text='Comma-separated keywords', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='eventspage',
            name='og_description',
            field=models.CharField(blank=True, help_text='Open Graph description for social media', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='eventspage',
            name='og_image',
            field=models.ImageField(blank=True, help_text='Open Graph image (1200x630px recommended)', null=True, upload_to='seo/og/'),
        ),
        migrations.AddField(
            model_name='eventspage',
            name='og_title',
            field=models.CharField(blank=True, help_text='Open Graph title for social media', max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='eventspage',
            name='og_type',
            field=models.CharField(blank=True, default='website', help_text='Open Graph type (e.g., website, article)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='eventspage',
            name='robots_follow',
            field=models.BooleanField(default=True, help_text='Allow search engines to follow links on this page', null=True),
        ),
        migrations.AddField(
            model_name='eventspage',
            name='robots_index',
            field=models.BooleanField(default=True, help_text='Allow search engines to index this page', null=True),
        ),
        migrations.AddField(
            model_name='eventspage',
            name='twitter_card',
            field=models.CharField(blank=True, default='summary_large_image', help_text='Twitter card type (summary, summary_large_image)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='eventspage',
            name='twitter_description',
            field=models.CharField(blank=True, help_text='Twitter card description (falls back to OG description)', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='eventspage',
            name='twitter_image',
            field=models.ImageField(blank=True, help_text='Twitter card image (falls back to OG image)', null=True, upload_to='seo/twitter/'),
        ),
        migrations.AddField(
            model_name='eventspage',
            name='twitter_title',
            field=models.CharField(blank=True, help_text='Twitter card title (falls back to OG title)', max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='luxurycamp',
            name='canonical_url',
            field=models.URLField(blank=True, help_text='Canonical URL (if different from current URL)', null=True),
        ),
        migrations.AddField(
            model_name='luxurycamp',
            name='meta_description',
            field=models.CharField(blank=True, help_text='Meta description (150-160 characters recommended)', max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='luxurycamp',
            name='meta_keywords',
            field=models.CharField(blank=True, help_text='Comma-separated keywords', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='luxurycamp',
            name='meta_title',
            field=models.CharField(blank=True, help_text='Meta title (50-60 characters recommended)', max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='luxurycamp',
            name='og_description',
            field=models.CharField(blank=True, help_text='Open Graph description for social media', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='luxurycamp',
            name='og_image',
            field=models.ImageField(blank=True, help_text='Open Graph image (1200x630px recommended)', null=True, upload_to='seo/og/'),
        ),
        migrations.AddField(
            model_name='luxurycamp',
            name='og_title',
            field=models.CharField(blank=True, help_text='Open Graph title for social media', max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='luxurycamp',
            name='og_type',
            field=models.CharField(blank=True, default='website', help_text='Open Graph type (e.g., website, article)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='luxurycamp',
            name='robots_follow',
            field=models.BooleanField(default=True, help_text='Allow search engines to follow links on this page', null=True),
        ),
        migrations.AddField(
            model_name='luxurycamp',
            name='robots_index',
            field=models.BooleanField(default=True, help_text='Allow search engines to index this page', null=True),
        ),
        migrations.AddField(
            model_name='luxurycamp',
            name='twitter_card',
            field=models.CharField(blank=True, default='summary_large_image', help_text='Twitter card type (summary, summary_large_image)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='luxurycamp',
            name='twitter_description',
            field=models.CharField(blank=True, help_text='Twitter card description (falls back to OG description)', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='luxurycamp',
            name='twitter_image',
            field=models.ImageField(blank=True, help_text='Twitter card image (falls back to OG image)', null=True, upload_to='seo/twitter/'),
        ),
        migrations.AddField(
            model_name='luxurycamp',
            name='twitter_title',
            field=models.CharField(blank=True, help_text='Twitter card title (falls back to OG title)', max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='canonical_url',
            field=models.URLField(blank=True, help_text='Canonical URL (if different from current URL)', null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='meta_description',
            field=models.CharField(blank=True, help_text='Meta description (150-160 characters recommended)', max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='meta_keywords',
            field=models.CharField(blank=True, help_text='Comma-separated keywords', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='meta_title',
            field=models.CharField(blank=True, help_text='Meta title (50-60 characters recommended)', max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='og_description',
            field=models.CharField(blank=True, help_text='Open Graph description for social media', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='og_image',
            field=models.ImageField(blank=True, help_text='Open Graph image (1200x630px recommended)', null=True, upload_to='seo/og/'),
        ),
        migrations.AddField(
            model_name='tour',
            name='og_title',
            field=models.CharField(blank=True, help_text='Open Graph title for social media', max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='og_type',
            field=models.CharField(blank=True, default='website', help_text='Open Graph type (e.g., website, article)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='robots_follow',
            field=models.BooleanField(default=True, help_text='Allow search engines to follow links on this page', null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='robots_index',
            field=models.BooleanField(default=True, help_text='Allow search engines to index this page', null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='twitter_card',
            field=models.CharField(blank=True, default='summary_large_image', help_text='Twitter card type (summary, summary_large_image)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='twitter_description',
            field=models.CharField(blank=True, help_text='Twitter card description (falls back to OG description)', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='twitter_image',
            field=models.ImageField(blank=True, help_text='Twitter card image (falls back to OG image)', null=True, upload_to='seo/twitter/'),
        ),
        migrations.AddField(
            model_name='tour',
            name='twitter_title',
            field=models.CharField(blank=True, help_text='Twitter card title (falls back to OG title)', max_length=60, null=True),
        ),
    ]
