# Generated by Django 5.1.5 on 2025-02-20 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0077_aboutpage_canonical_url_aboutpage_meta_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventspage',
            name='meta_description',
            field=models.CharField(blank=True, help_text='Meta description (150-160 characters recommended)', max_length=160, null=True),
        ),
        migrations.AlterField(
            model_name='eventspage',
            name='meta_title',
            field=models.CharField(blank=True, help_text='Meta title (50-60 characters recommended)', max_length=60, null=True),
        ),
    ]
