# Generated by Django 5.1.5 on 2025-02-22 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0078_alter_eventspage_meta_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='short_title',
            field=models.CharField(blank=True, help_text='Shorter version of the title for menus and cards', max_length=100, null=True),
        ),
    ]
