# Generated by Django 5.1.5 on 2025-03-03 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0081_sitemapentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitiespage',
            name='meta_description',
            field=models.CharField(blank=True, help_text='Meta description (150-160 characters recommended)', max_length=160, null=True),
        ),
        migrations.AlterField(
            model_name='activitiespage',
            name='meta_keywords',
            field=models.CharField(blank=True, help_text='Comma-separated keywords', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='activitiespage',
            name='meta_title',
            field=models.CharField(blank=True, help_text='Meta title (50-60 characters recommended)', max_length=60, null=True),
        ),
    ]
