# Generated by Django 5.1.5 on 2025-03-03 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0082_alter_activitiespage_meta_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitiespage',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='activitiespage',
            name='subtitle',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='activitiespage',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
